import math
def  add(a,b):
    return a+b
def sub(a,b):
    return a-b
def mul(a,b):
    return a*b
def div(a,b):
    return a/b
def  mod(a,b):
    return a%b
def exp(a,b):
    return a**b
def floordiv(a,b):
    return a//b
def log(a,b):
    return a//b
def sqrt(a):
    return a**0.5
def sin(a):
    return math.sin(a)
def cos(a):
    return math.cos(a)
def tan(a):
    return math.tan(a)
def cot(a):
    return 1/math.tan(a)
def sec(a):
    return 1/math.cos(a)
def cosec(a):
    return 1/math.sin(a)
def factorial(a):
    return math.factorial(a)
def pi():
    return math.pi
def e():
    return math.e
def log10(a):
    return math.log10(a)
def log2(a):
    return math.log2(a)

        